language: python

python:
  - '3.6'
  - '3.7'

before_install:
  - pip install nose
  - pip install six
  - pip install coverage
  - pip install coveralls

install: pip install -r requirements.txt

script: make test

after_script: coveralls

notifications:
  email:
    recipients:
      - benjamin@bengfort.com
      - will@willz.org

    on_success: change
    on_failure: always
